version: '3'
services:
    nginx:
        image: nginx:1.13.6
        volumes:
            - ./:/var/www/html
            - ./docker/server/log/:/var/html/log
            - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        links:
            - php
        networks:
            self:
                ipv4_address: ${NGINX_HOST}
    php:
        build:
          context: docker/build/php
        user: 1000:1000
        links:
            - mysql
            - mysql_test
        volumes:
            - ./:/var/www/html
            - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/config/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/server/composer:/var/composer
        environment:
            COMPOSER_HOME: '/var/composer'
        extra_hosts:
            - 'api.shop.app:172.73.251.2'
        networks:
            self:
                ipv4_address: ${PHP_HOST}
    mysql:
        image: mysql:5.7.20
        environment:
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_USERNAME}
            MYSQL_DATABASE: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT}
        volumes:
            - ./docker/server/mysql:/var/lib/mysql
        networks:
            self:
                ipv4_address: ${MYSQL_HOST}
    mysql_test:
        image: mysql:5.7.20
        environment:
            MYSQL_USER: ${MYSQL_USERNAME_TEST}
            MYSQL_PASSWORD: ${MYSQL_USERNAME_TEST}
            MYSQL_DATABASE: ${MYSQL_PASSWORD_TEST}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_ROOT_TEST}
        volumes:
            - ./docker/server/mysql_test:/var/lib/mysql
        networks:
            self:
                ipv4_address: ${MYSQL_HOST_TEST}
    redis:
        image: redis:3.2
        networks:
            self:
                ipv4_address: ${REDIS_HOST}
    node:
        image: node:9.3.0
        working_dir: /var/www/html
        user: 1000:1000
        volumes:
            - ./:/var/www/html
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        environment:
            - cluster.name=shop-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./docker/server/elasticsearch:/usr/share/elasticsearch/data
        networks:
            self:
                ipv4_address: ${ELASTICSEARCH_HOST}
networks:
    self:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
